/**
 * Maps Prisma Tag.name (seed / DB) to `catalog.tags.<slug>` message keys.
 */
export const CATALOG_TAG_SLUG_BY_DB_NAME: Record<string, string> = {
  // ── GÉNERO ──────────────────────────────────────────────────────────────
  "Acción": "accion",
  "Aventura": "aventura",
  "Boys' Love": "boysLove",
  "Comedia": "comedia",
  "Crimen": "crimen",
  "Drama": "drama",
  "Fantasía": "fantasia",
  "Girls' Love": "girlsLove",
  "Histórico": "historico",
  "Horror": "horror",
  "Isekai": "isekai",
  "Magical Girls": "magicalGirls",
  "Mecha": "mecha",
  "Medicina": "medicina",
  "Misterio": "misterio",
  "Filosófico": "filosofico",
  "Psicológico": "psicologico",
  "Romance": "romance",
  "Sci-fi": "sciFi",
  "Slice of Life": "sliceOfLife",
  "Sobrenatural": "sobrenatural",
  "Deportes": "deportes",
  "Superhéroe": "superheroe",
  "Thriller": "thriller",
  "Tragedia": "tragedia",
  "Wuxia": "wuxia",

  // ── FORMATO ─────────────────────────────────────────────────────────────
  "4-Koma": "cuatroKoma",
  "Adaptación": "adaptacion",
  "Antología": "antologia",
  "Premio": "premio",
  "Fan Coloreado": "fanColoreado",
  "Full Color": "fullColor",
  "Long Strip": "longStrip",
  "Coloreado Oficial": "coloreado",
  "One-shot": "oneShot",
  "Autopublicado": "autopublicado",
  "Webcomic": "webcomic",

  // ── TEMÁTICA ─────────────────────────────────────────────────────────────
  "Aliens": "aliens",
  "Animales": "animales",
  "Cocina": "cocina",
  "Crossdressing": "crossdressing",
  "Delincuentes": "delincuentes",
  "Demonios": "demonios",
  "Genderswap": "genderswap",
  "Fantasmas": "fantasmas",
  "Gyaru": "gyaru",
  "Harem": "harem",
  "Loli": "loli",
  "Mafia": "mafia",
  "Magia": "magia",
  "Mahjong": "mahjong",
  "Artes Marciales": "artesMarciales",
  "Militar": "militar",
  "Chicas Monstruo": "chicas_monstruo",
  "Monstruos": "monstruos",
  "Música": "musica",
  "Ninja": "ninja",
  "Oficinistas": "oficinistas",
  "Policía": "policia",
  "Post-Apocalíptico": "postApocaliptico",
  "Reencarnación": "reencarnacion",
  "Harem Inverso": "haremInverso",
  "Samurai": "samurai",
  "Escuela": "escuela",
  "Shota": "shota",
  "Supervivencia": "supervivencia",
  "Viaje en el tiempo": "viajeTiempo",
  "Vampiros": "vampiros",
  "Videojuegos": "videojuegos",
  "Villana": "villana",
  "Realidad Virtual": "realidadVirtual",
  "Zombis": "zombis",

  // ── CONTENIDO ────────────────────────────────────────────────────────────
  "Gore": "gore",
};
